version: "3.4"

services:
  zookeeper:
    image: bitnami/zookeeper:3.8.2
    restart: always
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - default
  kafka:
    image: bitnami/kafka:3.5.1
    ports:
      - "9092:9092"
    restart: always
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper
    networks:
      - default
  mysql:
    image: mysql:8.1.0
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'caoc'
      MYSQL_PASSWORD: 'Caoc12345*'
      MYSQL_ROOT_PASSWORD: 'Caoc12345*'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - default
volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  mysql_data:
    driver: local
  mongodb_data:
    driver: local
networks:
  default:
    external: true
    name: bankingNetwork
